GET http://localhost:4000/room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4yIiwiaWF0IjoxNjM3NzY3ODAxfQ.lkt59TnUE_o9ltdD3t-2YMNEuIPh875UGtjmCWpcDRY

###
DELETE http://localhost:4000/room/619ea999da579a3d39167a67
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4yIiwiaWF0IjoxNjM3NzY3ODAxfQ.lkt59TnUE_o9ltdD3t-2YMNEuIPh875UGtjmCWpcDRY

### 
POST http://localhost:4000/room/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4yIiwiaWF0IjoxNjM3NzY3ODAxfQ.lkt59TnUE_o9ltdD3t-2YMNEuIPh875UGtjmCWpcDRY
Content-Type: application/json

{
    "adminID": "6195898fc0c8b73e436c0f5f",
    "otherUserID": "61958f77c68fa38feb031807"
}

### 
PATCH http://localhost:4000/room/6194ed8b3de160bd271fc8f9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MzcxODk2MzV9.c5eRuno8Pfk-cNl1H2yevEvkcjwt7Fr4xKRGJctne5k
Content-Type: application/json

{
    "delegatedTasks": "admin task 4"
}