GET http://localhost:4000/room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MzcxODk2MzV9.c5eRuno8Pfk-cNl1H2yevEvkcjwt7Fr4xKRGJctne5k

### 
POST http://localhost:4000/room/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MzcxOTAzMzF9.HdExtsz3mwywZYBA_vJfln1JUBUtjaeFNW3Hd7W0pQg
Content-Type: application/json

{
    "adminID": "6195898fc0c8b73e436c0f5f",
    "otherUserID": "61958f77c68fa38feb031807",
    "delegatedTasks": ["admin item 7", "admin item 8", "admin item 9"]
}

### 
PATCH http://localhost:4000/room/6194ed8b3de160bd271fc8f9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MzcxODk2MzV9.c5eRuno8Pfk-cNl1H2yevEvkcjwt7Fr4xKRGJctne5k
Content-Type: application/json

{
    "delegatedTasks": "admin task 4"
}

###
DELETE http://localhost:4000/room/6195870d41cfde00193d563d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MzcxODk2MzV9.c5eRuno8Pfk-cNl1H2yevEvkcjwt7Fr4xKRGJctne5k
