
GET http://localhost:3000/users

### 
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Logan",
    "husbandOfUser": [{"husband":"Josh"}]
}

###
DELETE http://localhost:3000/users/61675ff0938aa654107debac


###

GET http://localhost:3000/users/:id/usertasks

###

GET http://localhost:3000/users/:id/usertasks/:id