GET http://localhost:4000/room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2Mzc0MDk0NTJ9.MLJ80crvdbiHhItLuWvGruAef95R5rkuXdVyvuMNr3o

###
DELETE http://localhost:4000/room/6198f12c6704a638f6cbd264
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2Mzc0MDk0NTJ9.MLJ80crvdbiHhItLuWvGruAef95R5rkuXdVyvuMNr3o


### 
POST http://localhost:4000/room/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2Mzc0MDk0NTJ9.MLJ80crvdbiHhItLuWvGruAef95R5rkuXdVyvuMNr3o
Content-Type: application/json

{
    "adminID": "618ea65c0da045c386122036",
    "otherUserID": "6198e269681bda67f29079ee",
    "delegatedTasks": ["admin item 7", "admin item 8", "admin item 9"]
}

### 
PATCH http://localhost:4000/room/6194ed8b3de160bd271fc8f9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MzcxODk2MzV9.c5eRuno8Pfk-cNl1H2yevEvkcjwt7Fr4xKRGJctne5k
Content-Type: application/json

{
    "delegatedTasks": "admin task 4"
}

