
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGVsZ2EiLCJpYXQiOjE2MzUzNzI2OTN9.Le__7aCGjEwQ_yZi_Kejxm_IQT7Okicc5pnB6ok_Cws

### 
POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "John",
    "userpassword": "John"
}

###
DELETE http://localhost:4000/users/6179b9f4951b1849fac16a98
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImlhdCI6MTYzNTM2NzgxMH0.lFxp77CUMzo_FD_ev4Za83vYWalv5bELqhsAjsAmmSk

###
GET http://localhost:4000/users