
GET http://localhost:3000/users

### 
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John",
    "husbandOfUserID": "6169dfa0a68524e67a5b3678"
}

###
DELETE http://localhost:3000/users/6169e3d3ee84c7b8b83073cb


###

GET http://localhost:3000/users/:id/usertasks

###

GET http://localhost:3000/users/:id/usertasks/:id